### ISSUE TITLE
corrupt image checking?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#143]
had some images being corrupt at a point (about 1k) when importing for a new Server set up.
all the images files that had errors was having images with the size of 70bytes.
maybe we can have the server to check the file sizes of all the pictures and files and set minimum limits on the file/images (say anything over 1kb).
that way corruption and download errors will be corrected over time.

ofc issuing a new download of the faulty files is a must at this point aswell IMO.

also find issues with the Series Groups that had these issues and it locks up JMM desktop when it tries to load the Groups.

**Comment by AreFinstad** [comment]
note that this is only an issue if the user is offline it seems. 
not always online here anymore and things evened itself out once JMM got online and got new files.
still shouldnt happen IMO even without a connection to the web. the freezing i had that followed this also stopped once it had downloaded some metadata and images.

**Comment by maxpiva** [comment]
+1, problem is finding a way to detect broken images. Loading not always
give you error, only visual errors.

**Comment by AreFinstad** [comment]
well that is why i talk about file sizes.... a simple but not flawless way of detecting it IMO.
the smallest picture i have in my JMM server is a 971Byte png file of the english flag...... unsure why JMM got this since i dont use anything other than JMM Desktop (With Plex and ENBY) so i dont know about the characters it has to storage. (another thing that needs to be added IMO :D ) 

we could look for the smallest image file in AniDB and then set that as the minimum limit for "good" files. if files have not started downloading yet have allocated a file spot in the windows folders then its size have always been at 70bytes for me. 

so far i have only 2 pictures that is smaller than 1.39KB and they are both the same picture even.
![](http://puu.sh/htltz/892ac1d57d.png)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Already references in main server issue.
