### ISSUE TITLE
Button for Opening Location folder for images (thumbnail images aswell) 

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#156]
great if you want to use the pictures for something else like another media server or swap the pictures out for better once (or edited)
only way to do it now if to open it in your picture viewer and then open the location for that.
better off with a button that just opens the folder and then highlights it like many other programs of that kind. i think we have room for this in the UI (or even a hid-able button that will show it self when hovering over the picture (or just click the picture (instead of opening it i mean)))

**Comment by jmediamanager** [comment]
Yup should be fine, can probably bundle it in with the ability to specify your own images for posters/fanart etc

**Comment by AreFinstad** [comment]
YES! custom pictures would be great. would it be hard to say auto load something at the file location (like [FILENAME]-thumb.jpg for thumbnails and so on?

**Comment by jmediamanager** [comment]
My preference is use AniDB/TvDB, but allow the user to manually override by selection.

**Comment by AreFinstad** [comment]
well how i see the picture already work with JMM is that they are just numbered and registered in the JMM server (witch make it a bit harder for the user to find the folder and so on to add more/different pictures) you can have some kind of UI in JMM Desktop that let people import pictures then JMM will just copy it to its normal place.

the best way IMO is that JMM should use the picture with the file (not in the server location) if there is any, JMM should also be able to copy whatever file to the file location as an overwrite if you know what i mean.

this way JMM will always load pictures next to the file over what it has on the server, but also keep the pictures at hand, and by letting us overwrite whats next to the file in question then we will set the priority more easily since users can swap out files for whatever the server got on hand.

by setting up something like this it will also let other media servers to load those pictures without downloading new things from tvdb and so on. (ofc file naming has to be the same standard as the other servers for this to work.

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

Not possible in Web UI anyways.
