### ISSUE TITLE
Character Viewing in JMM Desktop?

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#163]
Character Viewing in JMM Desktop, we should be able to view everything in JMM Desktop..... even characters, why do we need to use MP or the Win8 app (that is a hassle at times to get working) to view such things.
wouldn't it be better to have another tab on the series page that all the characters are listed with some space (like the cards in the dashboard) that contain the character text, tags and specs/info (everything really) and by using the cards like you do on the dashboard then you
can give more room for the image aswell to the left side.

this is has alot more use now since AniDB have started tagging per character instead of series aswell (clickable tag search is a must IMO!)

**Comment by jmediamanager** [comment]
Yes I thought about this over the years, but the priority will probably always be low.
The reason for this is because in JMM Desktop, it will always be easy to just click the AniDB link and view the info in the browser (which is no possible in MP)

**Comment by AreFinstad** [comment]
true, but that also limits JMM to be THE place for all anime tho.
i personally HATE AniDB's design and we already have downloaded the info about the characters on the server. why not use it?

i love to check on characters but since im never really on AniDB at all unless its to add files on AVDump.
with it in Client it would be more convenient IMO.

also sorry for all the issues at once, havnet had internet in a good good while and i wrote down alot of thought on the program while using it offline, im still not done with my list XD

**Comment by jmediamanager** [comment]
Yeah I agree with having it there, but just saying the pririty is lower than other stuff :)

**Comment by AreFinstad** [comment]
i get you i get you :P

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
