### ISSUE TITLE
Better Searching

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#164]
Searching should search for custom tags aswell as episode and series text (and character text and tags once they get added into JMM Desktop)
we should also be able to search for just one field if we choose too. (drop-down menu to choose what to search for (like just tags, just characters and so on))

**Comment by t0815** [comment]
yes, in addition it would be better to have a "search"- button to start to search. Imo, automatically searching with each typed letter makes the whole search process unresponsive and slow.

**Comment by ElementalCrisis** [comment]
Personally I like the way the search function currently works. For more advanced searching like @AreFinstad suggest it makes sense to have a search button.

**Comment by AreFinstad** [comment]
well searching works fine for what it is ATM, but it could do so much more since JMM already handles all the info it needs to work correctly.

cuts and words from episode and series text (great to find that one episode you dont recall what was)
character tags (as JMM does support characters and their info but does not use it in JMMD ATM)
creators and studios is also a great thing to search for.


most of this can be done with Group Filters, but there really isnt any reason why it should not work with normal searches aswell. 

also i never find the searches are slow at all, they are lightning fast for me even if i have 2k groups.

dont mind having an old school search button tho, aslong as we can press enter to search and/or have an option to have the live search still intact (as its super fast for me and i would not change it)

everything that is searchable at AniDB should be searchable in JMM IMO as its is main metadata agent.
![](http://i.imgur.com/fa9gXA4.png)

ofc users are not needed, but everything else can have an use in JMM some way or another, even clubs (would love to have clubs in JMM BTW XD)

**Comment by jmediamanager** [comment]
Yup we can add an advanced search button I think.

With the current limitation on the search types is due to the fact it only looks at data that is cached in JMM Desktop itself (which is only a subset of the types of data)

An advanced search button would look at JMM Server/Databasew itself, and would require the user to his the 'Search' button

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
