### ISSUE TITLE
Bookmarks needs rework

### ISSUE THREAD

**Issue by CuddleBear92** [ShokoAnime/ShokoDesktop#222]
i think the bookmark system is fair, but its all 100% manual input, we should be able to more quickly manage it by say auto remove if series is complete and is on the server in the right language for example.
we should be able to set our filters for what counts to be removed from the Bookmarks list, like If the hole series is there and if its in the language and/or source type you like (so if you download a RAW it does not get removed or if you want BD releases above everything else)

also, i think we could have quick buttons like waiting for BD release and so on in the Bookmarks tab, i really do think there is alot that can be better with this tab, as the way it is now its very limited.

also, ALOT of wasted space on this tab (maybe have small tiles like the similar tab?)

**Comment by jmediamanager** [comment]
I think the whole concept of bookmarking needs to be reviewed.
Custom Tags now covers a lot of what this what was intended for.
I will come back to this.

**Comment by AreFinstad** [comment]
well an own Bookmarks tab is still better than having things in the Collection Tab IMO (as the list of series could be better to navigate for this usage)
but it could be crossed over IMO, if you have a Tag in "Waiting for BD" for example it would show up in the bookmarks tab and so on, not having the long list that waste space is also really needed for this tab too IMO.

**Comment by AreFinstad** [comment]
thought: if you add a series to Bookmarks you should have an option to auto add that series to your collection aswell as auto tagging with a custom tag (something that should be done after a setting the user have set) 

example, if you see a series you want that you don't have, you click add to bookmarks and that will add it like normally, but it will also add it to your Collection (downloading Metadata and so on) and Tag it with a Custom tag (that might be chosen by the user OR have a premade custom tag like "the waiting for BD" tag and so on) 

also with the UI change that i wrote about in the OP, we should maybe be able to open the series window of whatever series you choose (like the Metro Series view you just added) and maybe open in pinned aswell, since you already have added the series to the collection.

also think that bookmarks could be auto added if you have missing episodes/specials of series (should be able to add series to an ignore list (for larger series and series that have loads of things the user does not care about)) 
something like this could have an option for the user to choose if they want just normal episodes, episodes and specials and so on (maybe have a TVDB version where specials are integrated in the season counts as a normal episode)

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into.
