### ISSUE TITLE
First unwatched episode of random series

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#58]
**Reported by eskermikey, Jul 2, 2013**

Currently the 'Random Episode' button in a playlist gives you a completely random episode from either watched or unwatched episodes depending on setting. This results in the button being essentially pointless due to skipping over episodes.

I believe what would be far more useful would be a button that gives you the first unwatched episode of a random series within a playlist, so that you can mix things up but not end up watching a show out of sequence.

**Jul 3, 2013 werndlymob**

The Random button works as intended.

However, I'll add a random button on the playlist tab as well.

**Comment by misakitchi** [comment]
Can you please add this feature, "Smart Random", because its really usefull! :)

And i can you add a "Smart Random" button to "Continue Watching..." too?!
But as said eskermikey only the first unwatched episode and not the "Specials"

And same things for "Collection" a "Smart Random" button please :)

**Comment by misakitchi** [comment]
Please! I really need it!! 
=> "Smart Random Series"!
Because i lost lots of time only to choose what i want to watch... :(

**Comment by ElementalCrisis** [comment]
As Desktop is deprecated and in maintenance mode, the suggestion made in this issue will not be looked into. 

There is no random feature in the upcoming Web UI v4 nor is it planned,
