### ISSUE TITLE
Allow selecting multiple files in the Manually Linked list

### ISSUE THREAD

**Issue by lsahnicne** [ShokoAnime/ShokoDesktop#622]
## VERSION INFORMATION

Server Version: 4.1.2.0

Desktop Version: 4.1.2.0

## DESCRIPTION

I can select multiple files in the 'Unrecognized' list to manually link to a group. Then I want to AVDump these files from the 'Manually linked' list. But in this list, I can only select one at a time so it takes unnecessarily long. Please consider allowing multiple selections in this list.

**Comment by ElementalCrisis** [comment]
We are no longer actively working on Shoko Desktop but won't stop someone from making this change. Maybe @Baine or @Rawrskyes might want to take a look as both have recently worked on Desktop.

**Comment by Baine** [comment]
"unrecognized" is the main starting point for avdumping, due to the main reason that the intended workflow was
1. Find file(s) in unrecognized
2. AVDump them
3. add the files to AniDB
4. rescan the files any way (run import for all, run import on folder, rescan all in unrecognized or rescan the previously selected files in unrecognized)

the related buttons are present in the "manually linked" tool, but only for one off uses.
Adding multi select to that list would change the scope it was intended for,
and since the current desktop is in legacy mode this won't get implemented by myself.

Anybody else is welcome to pick this up again though.
