### ISSUE TITLE
JMM Desktop: Support to link to moviedb to show episode overview for standalone movies

### ISSUE THREAD

**Issue by jmediamanager** [ShokoAnime/ShokoDesktop#66]
**Reported by valkyria086, Sep 20, 2013**

Some of the movies are standalone, not related to any existing anime at all. (Kotonoha no Niwa, Redline, etc.)
For some there's no tvdb link exist for it. But The Movie DB does.
And because of this, those which doesn't have the tvdb link will have their episode overview empty even though movie db have nice images and descriptions for them.
It'd be nice if JMMD will select from movie db if it couldn't detect any link from tvdb.

**Comment by CatmanIX** [comment]
Adding to this since my issue wasn't exactly a duplicate:

Being able to link MovieDB entries directly to epsiodes, for multi-movie series like [GITS: Arise](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=9658) and [Mardock Scramble](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=7439) would be nice. GITS: Arise is related to a normal series so it does have TVDB data to pull from at least, but Mardock Scramble does not.

**Comment by ElementalCrisis** [comment]
Expanding support for TMDB is planned. 

Closing as this is a server issue, not desktop issue.
